# SLURM backend for DDBJ.
call-caching {
  enabled = true
}

system {
  file-hash-cache = true
}

docker {
  hash-lookup {
    enabled = false
  }
}

database {
  profile = "slick.jdbc.HsqldbProfile$"
  db {
    driver = "org.hsqldb.jdbc.JDBCDriver"
    url = "jdbc:hsqldb:file:cromwell-db/cromwell;shutdown=true;hsqldb.default_table_type=cached"
    connectionTimeout = 120000
    numThreads = 32
  }
}

backend {
  default = "SLURM"
  providers {
    SLURM {
      actor-factory = "cromwell.backend.impl.sfs.config.ConfigBackendLifecycleActorFactory"
      config {
        root = "cromwell-executions"
        filesystems {
          local {
            localization: ["hard-link", "copy"]
            caching {
              duplication-strategy: ["hard-link", "copy"]
              hashing-strategy: "fingerprint"
            }
          }
        }

        runtime-attributes = """
          Int cpu = 1
          Float? memory_gb
          String? docker
        """

        submit = """
          basedir="$GATKSV_SS_ROOT"
          "$basedir"/submit-nonsingularity-job-slurm.sh "${memory_gb}" "${cpu}" "$basedir" "${job_name}" "${cwd}" "${out}" "${err}" "" "${docker}" "${script}"
        """

        submit-docker = """
          basedir="$GATKSV_SS_ROOT"
          "$basedir"/submit-singularity-job-slurm.sh "${memory_gb}" "${cpu}" "$basedir" "${job_name}" "${cwd}" "${out}" "${err}" "" "${docker}" "${script}"
        """

        exit-code-timeout-seconds = 120
        job-id-regex = "(\\d+)(?:;.*)?"

        kill = "scancel ${job_id}"
        kill-docker = "scancel ${job_id}"

        check-alive = """
          basedir="$GATKSV_SS_ROOT"
          "$basedir"/check-alive-slurm.sh ${job_id}
        """

        concurrent-job-limit = 200
        maxRetries = 5
      }
    }
  }
}
