#sge-hardlink-singularity-cache-retry-check-fingerprint-postgres.conf
# Call Cacheを有効化し、同じデータに対して同じ処理をするときには以前使ったデータを再利用する
call-caching {
  enabled = true
}

# ファイルのハッシュをキャッシュしておく
system {
  file-hash-cache = true
}

# コンテナイメージのハッシュを使ってsingularityを起動しないようにするため
docker {
  hash-lookup {
    enabled = false
  }
}

# データベースに接続する
# しなくても使えないことはないがcall cacheを使うためには必須
database {
  profile = "slick.jdbc.PostgresProfile$"
  db {
    driver = "org.postgresql.Driver"
    url = "jdbc:postgresql://localhost:5432/cromwell"
    user = "cromwell"
    password = "cromwellpw"
    connectionTimeout = 120000
    numThreads = 32
  }
}

backend {
  default = "SGE"
  providers {
    SGE {
      actor-factory = "cromwell.backend.impl.sfs.config.ConfigBackendLifecycleActorFactory"
      config {
        root = "cromwell-executions"
        filesystems {
          local {
            localization: ["hard-link", "copy"]
            caching {
              duplication-strategy: ["hard-link", "copy"]
              hashing-strategy: "fingerprint"
            }
          }
        }

        # 実行時パラメータとして受け入れるものを指定
        # CPUコア数と利用メモリ、docker imageが指定でき、docker imageはオプション扱い
        #memory_gbは本来-l h_vmem=$MEM_G_PER_COREでqsubの制限として使用可能だけど、このconfではあえて使わない
        runtime-attributes = """
          Int cpu = 1
          Float memory_gb = 4
          String? docker
        """

        # Singularityを使わない場合のジョブの投入
        # 最初にスロットあたりのメモリ使用量を計算し、それを元にmem_reqとs_vmemの２つのパラメータを設定している
        submit = """
          basedir="/SSD_ARRAY/gatk-sv_v2024-06-26/tmp"
          "$basedir"/submit-nonsingularity-job.sh "${memory_gb}" "${cpu}" "$basedir" "${job_name}" "${cwd}" "${out}" "${err}" "" "${docker}" "${script}"
        """
        # Singularityを使う場合のジョブの投入
        # 最初にスロットあたりのメモリ使用量を計算し、それを元にmem_reqとs_vmemの２つのパラメータを設定している
        submit-docker = """
          basedir="/SSD_ARRAY/gatk-sv_v2024-06-26/tmp"
          singularitydir="/suikou/tool9-all/bin"
          "$basedir"/submit-singularity-job.sh "${memory_gb}" "${cpu}" "$basedir" "${job_name}" "${cwd}" "${out}" "${err}" "$singularitydir" "${docker}" "${script}"
        """

        # 120秒おきにqstatを実行しジョブの実行状況を確認する
        exit-code-timeout-seconds = 120

        # Job IDのフォーマット
        # qsubの結果の標準出力がどのようになっているか指定する
        job-id-regex = "(\\d+)"

        # Jobをキャンセルしたいときに実行するコマンド
        kill = "qdel ${job_id}"
        kill-docker = "qdel ${job_id}"

        # Jobの実行状況を確認するためのコマンド
        check-alive = """
          basedir="/SSD_ARRAY/gatk-sv_v2024-06-26/tmp"
          "$basedir"/check-alive.sh ${job_id}
        """

        # 同時に投入するジョブの数
        # ここを超えるジョブ数はcromwellのキューでまち状態になる
        concurrent-job-limit = 1000

        # ジョブ再試行回数
        maxRetries = 5

      }
    }
  }
}
